# Generated by Django 5.0.7 on 2024-08-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Task name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Queue.'), (1, 'In progress...'), (2, 'Completed!')], default=0, null=True, verbose_name='Status')),
            ],
            options={
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
